spring.application.name=exemplo2-spring-boot-turmaC#

# URL deconexão de banco 
spring.datasource.url=jdbc:h2:nem:bancoteste


#usuario padrão 
spring.datasource.username=sa
#senha do usuario padrão
spring.datasource.password=


#habilita console do H2
spring.h2.console.enabled=true
#URL de acesso do console do H2
spring.h2.console.path=/h2-console

#Atualização a estrutura do banco basseada nas clsses java 
spring.jpa.hibernate.dll-auto=update
